# Default values for eos-block-producer-with-failover.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "activeeos/eos-with-nodeos-monitor"
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

persistence:
  enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  annotations: {}
  accessMode: ReadWriteOnce
  size: 8Gi

nodeSelector: {}

tolerations: []

affinity:
  # This makes it so BPs are placed on different nodes.
  # podAntiAffinity:
  #   preferredDuringSchedulingIgnoredDuringExecution:
  #   - weight: 100
  #     podAffinityTerm:
  #       topologyKey: "failure-domain.beta.kubernetes.io/zone"


nodeosConfig:
  # Unfortunately, this has to be defined when the server is first
  # booted, then dropped.
  defineGenesis: true

  deleteAllBlocks: false
  replayBlockchain: false

  # This is applied to the pod label "nodeGroup"
  nodeGroup: "bps"

nodeosMonitorConfig:
  failoverGroup: 'eos-bp'
  etcd:
    endpoint: 'http://127.0.0.1:2379'

# The initial genesis state.
genesis: |
  {
    "initial_timestamp": "2018-03-02T12:00:00.000",
    "initial_key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
    "initial_configuration": {
      "max_block_net_usage": 1048576,
      "target_block_net_usage_pct": 1000,
      "max_transaction_net_usage": 524288,
      "base_per_transaction_net_usage": 12,
      "net_usage_leeway": 500,
      "context_free_discount_net_usage_num": 20,
      "context_free_discount_net_usage_den": 100,
      "max_block_cpu_usage": 100000,
      "target_block_cpu_usage_pct": 500,
      "max_transaction_cpu_usage": 50000,
      "min_transaction_cpu_usage": 100,
      "max_transaction_lifetime": 3600,
      "deferred_trx_expiration_window": 600,
      "max_transaction_delay": 3888000,
      "max_inline_action_size": 4096,
      "max_inline_action_depth": 4,
      "max_authority_depth": 6,
      "max_generated_transaction_count": 16
    },
    "initial_chain_id": "0000000000000000000000000000000000000000000000000000000000000000"
  }

# Specify this to load active configs from a secret.
activeConfigSecret:
  enabled: false
  name: ""
  key: "config.ini"

# Specify this to load standby configs from a secret.
standbyConfigSecret:
  enabled: false
  name: ""
  key: "config.ini"

# Configuration for the active block producer.
activeConfig: |
  get-transactions-time-limit = 3
  block-log-dir = "blocks"
  max-reversible-block-time = -1
  max-pending-transaction-time = -1
  http-server-address = 0.0.0.0:8888
  p2p-listen-endpoint = 0.0.0.0:9876
  access-control-allow-origin = *
  mongodb-queue-size = 256
  agent-name = "Active"
  allowed-connection = any
  log-level-net-plugin = info
  max-clients = 25
  connection-cleanup-period = 30
  network-version-match = 1
  sync-fetch-span = 1000
  enable-stale-production = true
  required-participation = 33
  producer-name = eosio
  plugin = eosio::net_plugin
  plugin = eosio::producer_plugin
  plugin = eosio::chain_api_plugin
  plugin = eosio::history_plugin
  plugin = eosio::history_api_plugin

# Configuration for the standby block producer.
standbyConfig: |
  get-transactions-time-limit = 3
  block-log-dir = "blocks"
  max-reversible-block-time = -1
  max-pending-transaction-time = -1
  http-server-address = 0.0.0.0:8888
  p2p-listen-endpoint = 0.0.0.0:9876
  access-control-allow-origin = *
  mongodb-queue-size = 256
  agent-name = "Standby"
  allowed-connection = any
  log-level-net-plugin = info
  max-clients = 25
  connection-cleanup-period = 30
  network-version-match = 1
  sync-fetch-span = 1000
  enable-stale-production = false
  required-participation = 33
  plugin = eosio::net_plugin
  plugin = eosio::chain_api_plugin
  plugin = eosio::history_plugin
  plugin = eosio::history_api_plugin
