# Default values for eos-block-producer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

eosImage:
  repository: eosio/eos
  tag: latest
  pullPolicy: Always

caddyImage:
  repository: abiosoft/caddy
  tag: latest
  pullPolicy: Always

wireguardImage:
  repository: activeeos/wireguard-docker
  tag: latest
  pullPolicy: Always

# This is applied to the pod label "nodeGroup"
nodeGroup: "validators"

service:
  type: ClusterIP
  onlyWireguardPorts: false

ingress:
  enabled: false
  # hosts:
    # - chart-example.local
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   kubernetes.io/tls-acme: "true"
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

persistence:
  enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  annotations: {}
  accessMode: ReadWriteOnce
  size: 8Gi

wireguard:
  enabled: false

  # This is the UDP port that Wireguard will listen on.
  port: 5555

  # This should be filled out with configuration for a Wireguard
  # interface.
  interfaceConfig: ""

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

caddyfile: |
  :80

  # For TLS, replace this with your block producer's domain, insert
  # your email here, and remove "http://localhost:80" from above
  ## bp.com
  ## tls user@host.com

  proxy / localhost:8888

genesis: |
  {
    "initial_key": "EOS55xgWhiYohaHtFTxcPMorB9MzwBfe3JgUuQEujrurmHLHiXmna",
    "initial_timestamp": "2018-04-06T00:00:00",
    "initial_parameters": {
      "maintenance_interval": 86400,
      "maintenance_skip_slots": 3,
      "maximum_transaction_size": 2048,
      "maximum_block_size": 2048000000,
      "maximum_time_until_expiration": 86400,
      "maximum_producer_count": 1001
    },
    "immutable_parameters": {
      "min_producer_count": 42
    },
    "initial_chain_id": "00000000000000000000000000000000003c332053555045524845524f203c33"
  }

# Specify this to load configs from a secret.
configSecret:
  enabled: false
  name: ""
  key: "config.ini"

config: |
  get-transactions-time-limit = 3
  block-log-dir = "blocks"
  max-reversible-block-time = -1
  max-pending-transaction-time = -1
  http-server-address = 0.0.0.0:8888
  p2p-listen-endpoint = 0.0.0.0:9876
  access-control-allow-origin = *
  mongodb-queue-size = 256
  agent-name = "Standby"
  allowed-connection = any
  log-level-net-plugin = info
  max-clients = 25
  connection-cleanup-period = 30
  network-version-match = 1
  sync-fetch-span = 1000
  enable-stale-production = false
  required-participation = 33
  plugin = eosio::net_plugin
  plugin = eosio::chain_api_plugin
  plugin = eosio::history_plugin
  plugin = eosio::history_api_plugin
