{{ if not .Values.activeConfigSecret.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eos-block-producer-with-failover.fullname" . }}-nodeos-active
data:
  config.ini: |
{{ .Values.activeConfig | indent 4 }}
{{ end }}
