apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "eos-block-producer-with-failover.fullname" . }}
  labels:
    app: {{ template "eos-block-producer-with-failover.name" . }}
    chart: {{ template "eos-block-producer-with-failover.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    activeeos.io/bp: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: {{ template "eos-block-producer-with-failover.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "eos-block-producer-with-failover.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: nodeos-active-config
          configMap:
            name: {{ template "eos-block-producer-with-failover.fullname" . }}-nodeos-active
        - name: nodeos-standby-config
          configMap:
            name: {{ template "eos-block-producer-with-failover.fullname" . }}-nodeos-standby
        - name: nodeos-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "eos-block-producer-with-failover.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}-nodeos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["/opt/eosio/bin/nodeos-monitor", "--nodeos-args", "--data-dir=/var/eos-bp",
          {{- if .Values.nodeosConfig.replayBlockchain }}
                 "--nodeos-args", "--replay-blockchain",
          {{- end }}
          {{- if .Values.nodeosConfig.resyncBlockchain }}
                 "--nodeos-args", "--resync-blockchain",
          {{- end }}
                 "--log-format=json",
                 "--etcd-endpoints={{ .Values.nodeosMonitorConfig.etcd.endpoint }}",
                 "--failover-group={{ .Values.nodeosMonitorConfig.failoverGroup }}",
                 "--debug"]
          ports:
            - name: eos-p2p
              containerPort: 9876
              protocol: TCP
            - name: eos-http
              containerPort: 8888
              protocol: TCP
            - name: eos-bnet
              containerPort: 5887
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 600
            tcpSocket:
              port: 9876
          readinessProbe:
            tcpSocket:
              port: 9876
          volumeMounts:
            - name: nodeos-active-config
              mountPath: /etc/nodeos-active-configs
            - name: nodeos-standby-config
              mountPath: /etc/nodeos-standby-configs
            - name: nodeos-data
              mountPath: /var/eos-bp
              subPath: nodeos-data
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
