apiVersion: v1
kind: Service
metadata:
  name: {{ template "eos-block-producer-with-failover.fullname" . }}
  labels:
    app: {{ template "eos-block-producer-with-failover.name" . }}
    chart: {{ template "eos-block-producer-with-failover.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: eos-p2p
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: eos-http
    - port: 5887
      targetPort: 5887
      protocol: TCP
      name: eos-bnet
  selector:
    app: {{ template "eos-block-producer-with-failover.name" . }}
    release: {{ .Release.Name }}
