apiVersion: v1
kind: Service
metadata:
  name: {{ template "eos-block-producer.fullname" . }}
  labels:
    app: {{ template "eos-block-producer.name" . }}
    chart: {{ template "eos-block-producer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9876
      targetPort: 9876
      protocol: TCP
      name: eos-p2p
    - port: 80
      targetPort: 80
      protocol: TCP
      name: eos-http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: eos-https
  selector:
    app: {{ template "eos-block-producer.name" . }}
    release: {{ .Release.Name }}
